import 'package:dartz/dartz.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:health_pro/core/errors/failures.dart';
import 'package:health_pro/core/theme/app_theme.dart';
import 'package:health_pro/core/widgets/progress_ring.dart';
import 'package:health_pro/domain/entities/food.dart';
import 'package:health_pro/domain/entities/plan.dart';
import 'package:health_pro/domain/repositories/billing_repository.dart';
import 'package:health_pro/domain/repositories/diary_repository.dart';
import 'package:health_pro/domain/repositories/plan_repository.dart';
import 'package:health_pro/presentation/features/home/home_controller.dart';
import 'package:health_pro/presentation/features/plan/plan_page.dart';
import 'package:health_pro/presentation/l10n/app_localizations.dart';

import 'fakes.dart';

Widget planUnderTest(PlanRepository repo, {double textScale = 1}) {
  Get
    ..reset()
    ..put<PlanRepository>(repo, permanent: true);
  return GetMaterialApp(
    theme: AppTheme.dark,
    builder: (context, child) => MediaQuery(
      data: MediaQuery.of(context).copyWith(textScaler: TextScaler.linear(textScale)),
      child: child!,
    ),
    localizationsDelegates: const [
      AppLocalizations.delegate,
      GlobalMaterialLocalizations.delegate,
      GlobalWidgetsLocalizations.delegate,
      GlobalCupertinoLocalizations.delegate,
    ],
    supportedLocales: AppLocalizations.supportedLocales,
    home: const Scaffold(body: PlanPage()),
  );
}

void main() {
  testWidgets('shows the day split across meal slots', (tester) async {
    // Tall surface so all three meal cards lay out — the assertion is about content, not scrolling.
    tester.view.physicalSize = const Size(1200, 4000);
    tester.view.devicePixelRatio = 1;
    addTearDown(tester.view.reset);

    await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
    await tester.pumpAndSettle();

    // "about 558 kcal at breakfast" is guidance; a lone daily figure is closer to a score
    // (docs/05 §6). The split is what makes this tab worth having.
    expect(find.text('Breakfast'), findsOneWidget);
    expect(find.text('558 kcal'), findsNWidgets(2));
    expect(find.text('744 kcal'), findsOneWidget);
    // The share and the suggestion count share one line under the slot name now (D-133), so the
    // finder reads the part that matters rather than the whole string.
    expect(find.textContaining('30% of your day'), findsNWidgets(2));
    // The coloured macro line sits on every COLLAPSED row now (D-136): breakfast and dinner
    // share the figures, so it appears twice.
    expect(find.text('P 38 g · C 67 g · F 16 g'), findsNWidgets(2));
  });

  testWidgets('the day total is shown once, above the split', (tester) async {
    await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
    await tester.pumpAndSettle();

    // The figure and the unit are one styled line now, so the finder reads the parts.
    expect(find.textContaining('1859'), findsOneWidget);
    expect(find.text('Daily target'), findsOneWidget);
    expect(find.text('Recommended for you'), findsOneWidget);
  });

  testWidgets('no plan offers to create one', (tester) async {
    final repo = FakePlanRepository();
    await tester.pumpWidget(planUnderTest(repo));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Create my plan'));
    await tester.pumpAndSettle();

    expect(repo.generated, 1);
  });

  testWidgets('a blocked plan shows the docs/05 §7 referral copy', (tester) async {
    const referral =
        "Based on what you've told us, a plan generated by an app isn't the right tool here.";
    await tester.pumpWidget(
      planUnderTest(
        FakePlanRepository(
          failure: const ApiFailure(referral, code: 'PLAN_GATE_BLOCKED', status: 422),
        ),
      ),
    );
    await tester.pumpAndSettle();

    await tester.tap(find.text('Create my plan'));
    await tester.pumpAndSettle();

    expect(find.textContaining("isn't the right tool here"), findsOneWidget);
  });

  testWidgets('a safety warning renders verbatim (rule 7)', (tester) async {
    const clamp = "We've set your daily target a little higher than your goal alone would suggest.";
    await tester.pumpWidget(
      planUnderTest(
        FakePlanRepository(
          plan: Plan(
            id: samplePlan.id,
            validFrom: samplePlan.validFrom,
            targets: samplePlan.targets,
            mealTargets: samplePlan.mealTargets,
            rulePackVersion: samplePlan.rulePackVersion,
            warnings: const [clamp],
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text(clamp), findsOneWidget);
  });

  testWidgets('Failed shows the server message with a retry', (tester) async {
    await tester.pumpWidget(
      planUnderTest(
        FakePlanRepository(
          currentResult: const Left(
            ApiFailure('We could not load your plan.', code: 'X', status: 500),
          ),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.text('We could not load your plan.'), findsOneWidget);
    expect(find.text('Try again'), findsOneWidget);
  });

  testWidgets('no state leaves an infinite spinner (rule 6)', (tester) async {
    await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
    await tester.pumpAndSettle();

    expect(find.byType(CircularProgressIndicator), findsNothing);
  });

  /// D-130. The engine has always sent a fibre and a water target beside the four macros; the app
  /// parsed four of them and drew the other two nowhere.
  group('the day target card (D-130)', () {
    const withExtras = Plan(
      id: 'p2',
      validFrom: '2026-08-25',
      targets: Macros(kcal: 1859, proteinG: 125, carbG: 223, fatG: 52),
      fibreG: 30,
      waterMl: 2310,
      rulePackVersion: '1.0.0',
      warnings: [],
      mealTargets: [
        MealTarget(slot: 'breakfast', pct: 0.3, kcal: 558, proteinG: 38, carbG: 67, fatG: 16),
      ],
    );

    testWidgets('shows the fibre and water targets the server sends', (tester) async {
      await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: withExtras)));
      await tester.pumpAndSettle();

      expect(find.text('Fibre'), findsOneWidget);
      // A target with no figure beside it: a food log row copies kcal and three macros, so fibre
      // EATEN is not a number this app holds, and "0 / 30" would be a lie of arithmetic.
      expect(find.text('30 g a day'), findsOneWidget);
      expect(find.text('0 / 2310 ml'), findsOneWidget);
    });

    testWidgets('a plan without them draws neither tile rather than a zero', (tester) async {
      await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
      await tester.pumpAndSettle();

      expect(find.text('Fibre'), findsNothing);
      expect(find.text('Water'), findsNothing);
    });

    /// The reference sells a subscription from this screen. Entitlements are the server's
    /// (CLAUDE.md rule 3) and there is no entitlement in the app yet, so there is no button that
    /// would take money for something nothing can unlock.
    /// D-135/D-136. The ring shipped invisible twice — under the photograph, then brand green on
    /// a brand-green header. The card is on the PALE tint now (the ground the ring's theme
    /// defaults were measured for), so the invariant is: the ring exists, and the percentage it
    /// carries is on screen.
    testWidgets('the ring renders with its percentage on the target card', (tester) async {
      final diary = FakeDiaryRepository(
        dayResult: const Right(
          DiaryDay(
            diaryDate: '2026-09-01',
            entries: [],
            totals: Macros(kcal: 180, proteinG: 6, carbG: 7, fatG: 15),
            targets: Macros(kcal: 1500, proteinG: 99, carbG: 183, fatG: 42),
          ),
        ),
      );
      // planUnderTest resets Get, so the diary has to be registered AFTER it builds the widget
      // value and BEFORE the pump that reads it.
      final app = planUnderTest(FakePlanRepository(plan: samplePlan));
      Get
        ..put<DiaryRepository>(diary, permanent: true)
        ..put(HomeController(diary: diary, plans: FakePlanRepository()), permanent: true);

      await tester.pumpWidget(app);
      await tester.pumpAndSettle();

      expect(find.byType(ProgressRing), findsOneWidget);
      // The percentage is on screen, against the PLAN's 1859 kcal target, not the day's copy of
      // it: 180/1859 rounds to 10. And the consumed/left line the reference draws under the bar.
      expect(find.text('10%'), findsOneWidget);
      expect(find.text('180 kcal consumed'), findsOneWidget);
      expect(find.text('1,679 kcal left'), findsOneWidget);
    });

    /// Rule 12 in the one place a photograph can break it: the bowl overlaps the card's corner,
    /// and the header's right padding is what keeps the figure out from under it.
    testWidgets('the target card survives 200 % text scale with the art on it', (tester) async {
      tester.view.physicalSize = const Size(1200, 4000);
      tester.view.devicePixelRatio = 1;
      addTearDown(tester.view.reset);

      await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: withExtras), textScale: 2));
      await tester.pumpAndSettle();

      expect(find.text('Daily target'), findsOneWidget);
      expect(tester.takeException(), isNull);
    });

    /// D-133: the collapsed card is one row. The macros and the food strip are behind the tap,
    /// because four cards' worth of them was a screen of things nobody had asked to see.
    testWidgets('a meal card opens to its detail rather than showing it all at once', (
      tester,
    ) async {
      tester.view.physicalSize = const Size(1200, 4000);
      tester.view.devicePixelRatio = 1;
      addTearDown(tester.view.reset);

      await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
      await tester.pumpAndSettle();

      // The FIRST slot opens ready — "here is what to eat next" — so breakfast's options area
      // (its suggested-food count and strip) is already on screen. Lunch's is behind a tap.
      expect(find.textContaining('suggested food'), findsOneWidget);
      expect(find.text('Dal tadka'), findsOneWidget);

      await tester.tap(find.text('Lunch'));
      await tester.pumpAndSettle();

      expect(find.textContaining('suggested food'), findsNWidgets(2));
    });

    /// D-136. Entitlements are the server's (rule 3): the pill and the banner exist now, but
    /// only the server's word renders them — docs/11 §10 names "upgrade CTA while subscribed" as
    /// a shipped defect of the old build.
    testWidgets('premium surfaces render only when the server says FREE', (tester) async {
      tester.view.physicalSize = const Size(1200, 4000);
      tester.view.devicePixelRatio = 1;
      addTearDown(tester.view.reset);

      final app = planUnderTest(FakePlanRepository(plan: samplePlan));
      Get.put<BillingRepository>(FakeBillingRepository(), permanent: true);
      await tester.pumpWidget(app);
      await tester.pumpAndSettle();

      expect(find.text('Go Premium'), findsNWidgets(2), reason: 'the pill and the banner');
    });

    testWidgets('a paying tier sees no sales pitch at all', (tester) async {
      final app = planUnderTest(FakePlanRepository(plan: samplePlan));
      Get.put<BillingRepository>(FakeBillingRepository(tier: 'PRO'), permanent: true);
      await tester.pumpWidget(app);
      await tester.pumpAndSettle();

      expect(find.textContaining('Premium'), findsNothing);
    });

    testWidgets('no billing answer means no sales pitch either', (tester) async {
      // The repository is absent entirely — a build without billing, or a test that is not
      // about it. Unknown is treated as subscribed, never as a sales opportunity.
      await tester.pumpWidget(planUnderTest(FakePlanRepository(plan: samplePlan)));
      await tester.pumpAndSettle();

      expect(find.textContaining('Premium'), findsNothing);
    });
  });
}
