import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { UserEntity } from '../../users/infrastructure/persistence/relational/entities/user.entity';
import type { EnergyBasis, WorkoutEntry, WorkoutRecord } from '../gym-types';

/// A finished workout. Everything derived — volume, records, energy — is computed by the server
/// when it is saved and stored on the row, the way `food_log` copies nutrition at log time: a later
/// edit to a MET value or an exercise never rewrites history.
@Entity({ name: 'gym_workout' })
@Index(['userId', 'diaryDate'])
@Index(['userId', 'startedAt'])
export class GymWorkoutEntity {
  /// Generated by the phone, so a retried save is the same row (D-244 migration note).
  @PrimaryColumn({ type: 'uuid' })
  id: string;

  @ManyToOne(() => UserEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user: UserEntity;

  @Column()
  userId: number;

  @Column({ type: 'integer', nullable: true })
  routineId: number | null;

  @Column({ type: 'varchar' })
  name: string;

  @Column({ type: 'timestamptz' })
  startedAt: Date;

  @Column({ type: 'timestamptz' })
  endedAt: Date;

  /// CLAUDE.md rule 8: from `diaryDateFor(startedAt)`, never the phone's calendar.
  @Column({ type: 'date' })
  diaryDate: string;

  @Column({ type: 'numeric', precision: 5, scale: 2, nullable: true })
  bodyWeightKg: string | null;

  @Column({ type: 'jsonb' })
  entries: WorkoutEntry[];

  @Column({ type: 'integer' })
  setsDone: number;

  @Column({ type: 'numeric', precision: 12, scale: 2 })
  volumeKg: string;

  @Column({ type: 'integer' })
  durationSec: number;

  /// D-242. Null when there was no body weight to estimate with — never 0 for "unknown".
  @Column({ type: 'integer', nullable: true })
  energyKcal: number | null;

  @Column({ type: 'jsonb', nullable: true })
  energyBasis: EnergyBasis | null;

  @Column({ type: 'jsonb', default: () => "'[]'" })
  prs: WorkoutRecord[];

  @Column({ type: 'boolean', default: false })
  isDemo: boolean;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;
}
