/// User-facing copy for engine gates and warnings.
///
/// **These strings are quoted verbatim from docs/05 §7, which says "use verbatim; do not
/// paraphrase".** The wording is the safety feature, not decoration around it. CLAUDE.md rule 7
/// makes this the ONLY text the app shows for these outcomes — the client never writes its own.
///
/// Do not edit without a clinician. docs/05 §8 sets the review cadence.

const BLOCKING_CONDITION =
  "Based on what you've told us, a plan generated by an app isn't the right tool here — your " +
  "needs depend on clinical details we can't see. Please speak to your doctor or a registered " +
  'dietitian. They may be happy to set targets that we can then help you follow day to day.';

const CLINICIAN_GATE =
  "This needs a clinician's input before we set your targets. Your coach can unlock it once " +
  "they've confirmed your doctor's guidance.";

const UNDER_18 =
  "Eatzify is built for adults, so we can't create a plan for you yet. Nutrition needs during " +
  'growth are different and are best handled with a doctor or a registered dietitian who can see ' +
  "the full picture. If you'd like, we can send information you could share with a parent or " +
  'guardian.';

const EATING_DISORDER =
  "Thanks for telling us. We're not going to set calorie or weight targets for you — that " +
  "wouldn't be safe or kind. Support from a professional who specialises in this makes a real " +
  "difference, and we're happy to help you find it.";

const SAFETY_CLAMP =
  "We've set your daily target a little higher than your goal alone would suggest. Going lower " +
  'than this isn’t safe or sustainable, and it usually slows results rather than speeding ' +
  'them up.';

/// Not a docs/05 §7 safety string: this is an input conflict the user can fix in a tap, so it names
/// the fix. It must still come from here, because CLAUDE.md rule 7 makes `user_message` the only
/// text the client shows and the client never writes its own.
export function mealPatternConflictMessage(required: number): string {
  return (
    `Because of a health condition you've told us about, your plan needs at least ${required} ` +
    'eating occasions a day. Change the number of meals in your profile and we can build it.'
  );
}

export const GATE_COPY: Record<string, string> = {
  ckd: BLOCKING_CONDITION,
  pregnancy: BLOCKING_CONDITION,
  lactation: BLOCKING_CONDITION,
  hyperthyroid: BLOCKING_CONDITION,
  type_1_diabetes: BLOCKING_CONDITION,
  bmi_critical: BLOCKING_CONDITION,
  insufficient_food_coverage: BLOCKING_CONDITION,
  // Routed separately: docs/05 §4 is explicit that an eating-disorder disclosure must never be
  // answered with a coach-unlock or a referral written for a different reason.
  eating_disorder: EATING_DISORDER,
  age_ineligible: UNDER_18,
  post_surgery_needs_clinician: CLINICIAN_GATE,
  clinician_review_required: CLINICIAN_GATE,
  underweight_review: CLINICIAN_GATE,
};

/// Every warning that means "we raised or capped your target for safety" carries the one approved
/// clamp string. docs/05 §7 has a single sentence for this, not one per code.
const CLAMP_WARNINGS = new Set([
  'deficit_suppressed_low_bmi',
  'deficit_capped_age',
  'deficit_capped_condition',
  'deficit_capped_absolute',
  'deficit_capped_weekly_rate',
  'target_raised_to_bmr',
  'target_raised_to_floor',
  'goal_forced_maintenance_low_bmi',
  'surplus_capped_absolute',
]);

export type UserFacingWarning = { code: string; user_message: string };

/// Warnings with no approved user-facing string are dropped rather than shown raw — an internal
/// code like `estimate_precision_reduced` is for the trace, not for a user.
export function warningsForUser(codes: readonly string[]): UserFacingWarning[] {
  const seen = new Set<string>();
  const out: UserFacingWarning[] = [];

  for (const code of codes) {
    if (!CLAMP_WARNINGS.has(code) || seen.has(SAFETY_CLAMP)) continue;
    seen.add(SAFETY_CLAMP);
    out.push({ code: 'safety_clamp_applied', user_message: SAFETY_CLAMP });
  }

  return out;
}

export function gateMessage(code: string): string {
  return GATE_COPY[code] ?? BLOCKING_CONDITION;
}
