import { readFileSync } from 'fs';
import { resolve } from 'path';
import { MigrationInterface, QueryRunner } from 'typeorm';

/// ADR-013 / D-241 … D-245: the Gym section.
///
/// - `energy_reference` holds the MET values that price a workout (D-242). They are rows, not code
///   (API rule 1), each carrying its Compendium of Physical Activities code so a number can be traced
///   and corrected in the admin panel. Rows with a `minSpeedKmh` form speed bands: a set is priced by
///   the highest band at or below its speed.
/// - `exercise` is the shared library (ownerUserId NULL), loaded from `config/exercises/library-v1.json`
///   (MIT dataset, D-244), plus each user's own exercises.
/// - `gym_profile`, `gym_routine` and `gym_workout` are one user's plan and log. A routine's exercise
///   list and a workout's entries are jsonb because each is read and written whole.
/// - `gym_workout.id` is generated by the phone, so a save retried after a dropped connection lands
///   once.
export class AddGym1758800000000 implements MigrationInterface {
  name = 'AddGym1758800000000';

  public async up(q: QueryRunner): Promise<void> {
    await q.query(`
      CREATE TABLE "energy_reference" (
        "key" character varying NOT NULL,
        "activity" character varying NOT NULL,
        "value" numeric(5,2) NOT NULL,
        "unit" character varying NOT NULL,
        "minSpeedKmh" numeric(4,1),
        "source" character varying NOT NULL,
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_energy_reference_key" PRIMARY KEY ("key"),
        CONSTRAINT "CHK_energy_reference_value" CHECK ("value" > 0),
        CONSTRAINT "CHK_energy_reference_unit" CHECK ("unit" IN ('MET', 'min'))
      )
    `);
    await q.query(
      `INSERT INTO "energy_reference" ("key", "activity", "value", "unit", "minSpeedKmh", "source") VALUES ${ENERGY_ROWS.map(
        (_, i) =>
          `($${i * 6 + 1}, $${i * 6 + 2}, $${i * 6 + 3}, $${i * 6 + 4}, $${i * 6 + 5}, $${i * 6 + 6})`,
      ).join(', ')}`,
      ENERGY_ROWS.flatMap((r) => [
        r.key,
        r.activity,
        r.value,
        r.unit,
        r.minSpeedKmh,
        r.source,
      ]),
    );

    await q.query(`
      CREATE TABLE "exercise" (
        "id" character varying(40) NOT NULL,
        "name" character varying NOT NULL,
        "bodyPart" character varying NOT NULL,
        "equipment" character varying NOT NULL,
        "target" character varying NOT NULL,
        "secondaryMuscles" jsonb NOT NULL DEFAULT '[]',
        "steps" jsonb NOT NULL DEFAULT '{"en":[],"hi":[]}',
        "description" text,
        "mediaKey" character varying,
        "energyActivity" character varying NOT NULL,
        "isBodyweight" boolean NOT NULL DEFAULT false,
        "ownerUserId" integer,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_exercise_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_exercise_owner" FOREIGN KEY ("ownerUserId")
          REFERENCES "user"("id") ON DELETE CASCADE
      )
    `);
    await q.query(
      `CREATE INDEX "IDX_exercise_owner" ON "exercise" ("ownerUserId")`,
    );
    // One person cannot have two "My Row" exercises; the library and other people are unaffected.
    await q.query(
      `CREATE UNIQUE INDEX "UQ_exercise_owner_name" ON "exercise" ("ownerUserId", lower("name")) WHERE "ownerUserId" IS NOT NULL`,
    );

    const library = JSON.parse(
      readFileSync(
        resolve(process.cwd(), 'config/exercises/library-v1.json'),
        'utf8',
      ),
    ) as LibraryRow[];
    for (let i = 0; i < library.length; i += INSERT_BATCH) {
      const batch = library.slice(i, i + INSERT_BATCH);
      await q.query(
        `INSERT INTO "exercise" ("id", "name", "bodyPart", "equipment", "target", "secondaryMuscles", "steps", "mediaKey", "energyActivity", "isBodyweight") VALUES ${batch
          .map((_, j) => {
            const o = j * 10;
            return `($${o + 1}, $${o + 2}, $${o + 3}, $${o + 4}, $${o + 5}, $${o + 6}, $${o + 7}, $${o + 8}, $${o + 9}, $${o + 10})`;
          })
          .join(', ')}`,
        batch.flatMap((e) => [
          e.id,
          e.name,
          e.body_part,
          e.equipment,
          e.target,
          JSON.stringify(e.secondary),
          JSON.stringify(e.steps),
          e.media_id,
          e.energy_activity,
          e.is_bodyweight,
        ]),
      );
    }

    await q.query(`
      CREATE TABLE "gym_profile" (
        "userId" integer NOT NULL,
        "week" jsonb NOT NULL DEFAULT '{}',
        "dayOverrides" jsonb NOT NULL DEFAULT '{}',
        "workingWeights" jsonb NOT NULL DEFAULT '{}',
        "restSec" integer NOT NULL DEFAULT 90,
        "effortScale" character varying NOT NULL DEFAULT 'off',
        "keepAwake" boolean NOT NULL DEFAULT true,
        "sound" boolean NOT NULL DEFAULT true,
        "bodyFigure" character varying NOT NULL DEFAULT 'male',
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_gym_profile_user" PRIMARY KEY ("userId"),
        CONSTRAINT "FK_gym_profile_user" FOREIGN KEY ("userId")
          REFERENCES "user"("id") ON DELETE CASCADE,
        CONSTRAINT "CHK_gym_profile_rest" CHECK ("restSec" BETWEEN 15 AND 600),
        CONSTRAINT "CHK_gym_profile_effort" CHECK ("effortScale" IN ('off', 'rir', 'rpe')),
        CONSTRAINT "CHK_gym_profile_figure" CHECK ("bodyFigure" IN ('male', 'female'))
      )
    `);

    await q.query(`
      CREATE TABLE "gym_routine" (
        "id" SERIAL NOT NULL,
        "userId" integer NOT NULL,
        "name" character varying NOT NULL,
        "icon" character varying NOT NULL DEFAULT 'strength',
        "progression" character varying NOT NULL DEFAULT 'linear',
        "exercises" jsonb NOT NULL DEFAULT '[]',
        "position" integer NOT NULL DEFAULT 0,
        "isDemo" boolean NOT NULL DEFAULT false,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_gym_routine_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_gym_routine_user" FOREIGN KEY ("userId")
          REFERENCES "user"("id") ON DELETE CASCADE,
        CONSTRAINT "CHK_gym_routine_progression"
          CHECK ("progression" IN ('off', 'linear', 'greyskull', 'double'))
      )
    `);
    await q.query(
      `CREATE INDEX "IDX_gym_routine_user" ON "gym_routine" ("userId")`,
    );

    await q.query(`
      CREATE TABLE "gym_workout" (
        "id" uuid NOT NULL,
        "userId" integer NOT NULL,
        "routineId" integer,
        "name" character varying NOT NULL,
        "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "endedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
        "diaryDate" date NOT NULL,
        "bodyWeightKg" numeric(5,2),
        "entries" jsonb NOT NULL,
        "setsDone" integer NOT NULL,
        "volumeKg" numeric(12,2) NOT NULL,
        "durationSec" integer NOT NULL,
        "energyKcal" integer,
        "energyBasis" jsonb,
        "prs" jsonb NOT NULL DEFAULT '[]',
        "isDemo" boolean NOT NULL DEFAULT false,
        "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_gym_workout_id" PRIMARY KEY ("id"),
        CONSTRAINT "FK_gym_workout_user" FOREIGN KEY ("userId")
          REFERENCES "user"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_gym_workout_routine" FOREIGN KEY ("routineId")
          REFERENCES "gym_routine"("id") ON DELETE SET NULL,
        CONSTRAINT "CHK_gym_workout_span" CHECK ("endedAt" >= "startedAt"),
        CONSTRAINT "CHK_gym_workout_energy" CHECK ("energyKcal" IS NULL OR "energyKcal" >= 0)
      )
    `);
    await q.query(
      `CREATE INDEX "IDX_gym_workout_user_day" ON "gym_workout" ("userId", "diaryDate")`,
    );
    await q.query(
      `CREATE INDEX "IDX_gym_workout_user_started" ON "gym_workout" ("userId", "startedAt")`,
    );
  }

  public async down(q: QueryRunner): Promise<void> {
    await q.query(`DROP INDEX "IDX_gym_workout_user_started"`);
    await q.query(`DROP INDEX "IDX_gym_workout_user_day"`);
    await q.query(`DROP TABLE "gym_workout"`);
    await q.query(`DROP INDEX "IDX_gym_routine_user"`);
    await q.query(`DROP TABLE "gym_routine"`);
    await q.query(`DROP TABLE "gym_profile"`);
    await q.query(`DROP INDEX "UQ_exercise_owner_name"`);
    await q.query(`DROP INDEX "IDX_exercise_owner"`);
    await q.query(`DROP TABLE "exercise"`);
    await q.query(`DROP TABLE "energy_reference"`);
  }
}

const INSERT_BATCH = 200;

type LibraryRow = {
  id: string;
  name: string;
  body_part: string;
  equipment: string;
  target: string;
  secondary: string[];
  steps: { en: string[]; hi: string[] };
  media_id: string | null;
  energy_activity: string;
  is_bodyweight: boolean;
};

type EnergyRow = {
  key: string;
  activity: string;
  value: number;
  unit: 'MET' | 'min';
  minSpeedKmh: number | null;
  source: string;
};

const met = (
  activity: string,
  code: string,
  value: number,
  what: string,
  minSpeedKmh: number | null = null,
): EnergyRow => ({
  key: `${activity}:${code}`,
  activity,
  value,
  unit: 'MET',
  minSpeedKmh,
  source: `Compendium of Physical Activities ${code}: ${what}`,
});

/// Compendium of Physical Activities (pacompendium.com), read 2026-09-19. Speed bands are the
/// Compendium's mph bands converted to km/h and rounded to 0.1.
const ENERGY_ROWS: EnergyRow[] = [
  met(
    'strength',
    '02054',
    3.5,
    'resistance training, multiple exercises, 8-15 reps',
  ),
  met(
    'calisthenics',
    '02022',
    3.8,
    'calisthenics (push-ups, pull-ups, lunges), moderate',
  ),
  met(
    'calisthenics_vigorous',
    '02020',
    7.5,
    'calisthenics (jumping jacks, burpees), vigorous',
  ),
  met('circuit', '02035', 5.0, 'circuit training, moderate effort'),
  met('elliptical', '02048', 5.0, 'elliptical trainer, moderate effort'),
  met('stair_treadmill', '02065', 9.3, 'stair treadmill ergometer, general'),
  met('rope_skipping', '02068', 11.0, 'rope skipping, general'),
  met('stationary_bike', '01200', 6.8, 'bicycling, stationary, general'),
  met('walk', '17349', 3.0, 'walking, treadmill, 2.0-2.4 mph, 0% grade', 0),
  met('walk', '17352', 3.5, 'walking, treadmill, 2.5-2.9 mph, 0% grade', 4.0),
  met('walk', '17355', 3.8, 'walking, treadmill, 3.0-3.4 mph, 0% grade', 4.8),
  met('walk', '17358', 4.8, 'walking, treadmill, 3.5-3.9 mph, 0% grade', 5.6),
  met('walk', '17361', 5.8, 'walking, treadmill, 4.0-4.4 mph, 0% grade', 6.4),
  met('walk', '17364', 6.8, 'walking, treadmill, 4.5-4.9 mph, 0% grade', 7.2),
  met('walk', '17367', 8.3, 'walking, treadmill, 5.0-5.5 mph, 0% grade', 8.0),
  met('run', '12026', 4.8, 'jogging, 2.6-3.7 mph', 0),
  met('run', '12028', 6.5, 'running, 4-4.2 mph', 6.4),
  met('run', '12029', 7.8, 'running, 4.3-4.8 mph', 6.9),
  met('run', '12030', 8.5, 'running, 5.0-5.2 mph', 8.0),
  met('run', '12045', 9.0, 'running, 5.5-5.8 mph', 8.9),
  met('run', '12050', 9.3, 'running, 6-6.3 mph', 9.7),
  met('run', '12060', 10.5, 'running, 6.7 mph', 10.8),
  met('run', '12070', 11.0, 'running, 7 mph', 11.3),
  met('run', '12080', 11.8, 'running, 7.5 mph', 12.1),
  met('run', '12090', 12.0, 'running, 8 mph', 12.9),
  met('run', '12100', 12.5, 'running, 8.6 mph', 13.8),
  met('run', '12110', 13.0, 'running, 9 mph', 14.5),
  met('run', '12115', 14.8, 'running, 9.3-9.6 mph', 15.0),
  met('run', '12130', 16.8, 'running, 11 mph', 17.7),
  met('run', '12132', 18.5, 'running, 12 mph', 19.3),
  met('run', '12134', 19.8, 'running, 13 mph', 20.9),
  met('run', '12135', 23.0, 'running, 14 mph', 22.5),
  {
    key: 'strength_set_cap',
    activity: 'strength_set_cap',
    value: 3,
    unit: 'min',
    minSpeedKmh: null,
    source:
      'Eatzify (D-242): the most workout time one done set and its rest may count, so a session left open does not inflate the estimate',
  },
];
